import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "@/store/Providers";
import TokenProvider from "@/components/TokenProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Memories",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <TokenProvider>{children}</TokenProvider>
        </Providers>
      </body>
    </html>
  );
}
